# Change these first
owner: pbrainbiz # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: PBrain landing
    url: https://www.pbrain.biz
  - name: PBrain tenant
    url: https://www.pbrain.biz/pbrain
  - name: PBrain demo
    url: https://demo.pbrain.biz
  - name: PBrain experience
    url: https://experience.pbrain.biz/panasonic/na-s106fr1bs
  - name: PBrain web channel
    url: https://www.pbrain.biz/chatbot/channelweb?id=52-107&index=0
  - name: PBrain CN landing
    url: https://www.pbraindemo.cn
  - name: PBrain CN tenant
    url: https://www.pbraindemo.cn/xiaomi-airpurifier
  - name: PBrain CN web channel
    url: https://www.pbraindemo.cn/chatbot/channelweb?id=4-68&index=1
  - name: PBrain system test tenant
    url: https://www.pbrain.appahoo.com/pbrain
  - name: PBrain system test web channel
    url: https://www.pbrain.appahoo.com/chatbot/channelweb?id=1-10&index=0

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
